### ISSUE TITLE
assert len(self.bbox_assigner) == anchors.size(-3) AssertionError

### ISSUE THREAD

**Issue by chyohoo** [TuSimple/SST#3]
Hi, I got this error after using the corrected version of config in #2.  The len of self.bbox_assigner I got is 2, the anchors.shape gives me the torch.Size([1, 500, 500, 3, 2, 7]).

**Comment by chyohoo** [comment]
Traceback (most recent call last):
  File "/home/chen_haoye/WS_SST/SST/tools/train.py", line 234, in <module>
    main()
  File "/home/chen_haoye/WS_SST/SST/tools/train.py", line 231, in main
    meta=meta)
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/models/detectors/base.py", line 58, in forward
    return self.forward_train(**kwargs)
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/models/detectors/voxelnet.py", line 94, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/models/dense_heads/anchor3d_head.py", line 354, in loss
    sampling=self.sampling)
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/models/dense_heads/train_mixins.py", line 80, in anchor_target_3d
    sampling=sampling)
  File "/home/chen_haoye/anaconda3/envs/SST/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/chen_haoye/WS_SST/SST/mmdet3d/models/dense_heads/train_mixins.py", line 131, in anchor_target_3d_single
    assert len(s

**Comment by chyohoo** [comment]
I modify the config from `sst_waymoD5_1x_ped_cyc_8heads_3f`, which takes 2 assigners. but I want to train the model with 3 classes so I modified the config as following:
`bbox_head=dict(
        type='Anchor3DHead',
        num_classes=3,
        in_channels=384,
        feat_channels=384,
        use_direction_classifier=True,
        anchor_generator=dict(
            type='AlignedAnchor3DRangeGenerator',
            ranges=[[-74.88, -74.88, -0.0345, 74.88, 74.88, -0.0345],
                    [-74.88, -74.88, -0.1188, 74.88, 74.88, -0.1188],
                    [-74.88, -74.88, 0, 74.88, 74.88, 0]],
            sizes=[
                [2.08, 4.73, 1.77],  # car
                [0.84, 1.81, 1.77],  # cyclist
                [0.84, 0.91, 1.74]  # pedestrian
            ],
....
`
And changed the class_name correspondingly.
Are there something else I need to change?

**Comment by chyohoo** [comment]
I found I have to add an assigner in train_cfg.
